version: '3'

services:
  frontend:
    container_name: canoe_frontend
    image: "nginx:alpine"
    depends_on:
      - backend
    volumes:
      - "./docker/frontend:/etc/nginx/templates"
      - "./:/app"
    ports:
      - ${NGINX_PORT}:80
    env_file:
      - ".env"
    networks:
      - local

  backend:
    container_name: canoe_backend
    depends_on:
      - db
    build:
      context: "./docker/backend/"
    volumes:
      - "./:/app"
    env_file:
      - ".env"
    networks:
      - local

  db:
    container_name: canoe_db
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - local

networks:
  local:
    driver: bridge

volumes:
  db_data: